version: '3.8'
services:
  stt:
    build:
      context: .
      dockerfile: service/stt/Dockerfile
    volumes:
      - ./models/asr25:/models/asr25:ro
    ports:
      - "8001:8001"

  llm:
    build:
      context: .
      dockerfile: service/llm/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BREEZE_API_KEY=${BREEZE_API_KEY}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BREEZE_API_KEY=${BREEZE_API_KEY}
    depends_on:
      - stt
      - llm

  db:
    image: nouchka/sqlite3
    volumes:
      - ./app/chat.db:/data/chat.db

